### ISSUE TITLE
切换 Server 必须重启服务才能生效

### ISSUE THREAD

**Issue by LitCcc** [ttimasdf/luci-app-xray#3]
在设置页面选择好tcp server和udp server，点保存并应用后依然是之前的server，必须重启服务才能使新的server配置生效

**Comment by ttimasdf** [comment]
Fixed in 19b0205

**Comment by ttimasdf** [comment]
不过实现比较粗糙😂按一下“保存并应用”按钮就重启一下服务，照着 luci-mod-system 写的（[crontab.js - openwrt/luci - GitHub1s](https://github1s.com/openwrt/luci/blob/HEAD/modules/luci-mod-system/htdocs/luci-static/resources/view/system/crontab.js)）。但大部分时候还是符合直觉的。

**Comment by sdandroid** [comment]
@ttimasdf  `/root/etc/init.d/xapp ` 这个文件改成这样就可以生效了。
```
service_triggers() {
    procd_add_reload_trigger "xapp"
}
```
